### ISSUE TITLE
Make the app as vuejs package or plugin

### ISSUE THREAD

**Issue by iashraful** [iashraful/awesome-select#1]
### Packaging
We must add the feature that anyone from anywhere can download/install and use as a traditional package. For example, we use various libraries with minimal configuration.

### Example
```
import AwesomeSelect from 'awesome-select'

...
components: { AwesomeSelect }
...
```

**Comment by shafikshaon** [comment]
Ok. I suggest to use component as usual way. If we use directive then we need to import vue. And it make unnecessary dependency with vue. In fact it cause error for other user if the use other version of vue.

**Comment by iashraful** [comment]
@shafikshaon  OK Go ahead

**Comment by iashraful** [comment]
@shafikshaon 
Please update `README.md` with details.

**Comment by iashraful** [comment]
npm: https://www.npmjs.com/package/awesome-select
