### ISSUE TITLE
Enabling option text and value customization

### ISSUE THREAD

**Issue by shafikshaon** [iashraful/awesome-select#3]
Option JSON can be key-value pair. We need to map value and label on `<option value="some_value"> Display text </option>` in dropdown. 

The idea is user has control over which values go on option value and which value goes on option label.

See the following example:
```
[
    {
        'id': 123,
        'display': 'Option 1'
    },
    {
        'id': 456,
        'display': 'Option 2'
    }
]
```

If a user has this JSON array then the user can choose is `id` goes to as option value or label.

A proposed solution.
```
<AwesomeSelect
     option-value="id"
     option-text="display"
/>
```
It's like html select
```
<select>
    <option value="123"> Option 1</option>
    <option value="456"> Option 2</option>
</select>
```

**Comment by iashraful** [comment]
There is support for this.  Two different props. They are, `labelKey` & `valueKey`. Both are string.
